## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID         City Country  Max Temp Current Description      Lat  \
0        0        Jerez      GT     81.05           clear sky  14.1000   
1        3   Butaritari      KI     81.97          light rain   3.0707   
2       11  East London      ZA     67.21     overcast clouds -33.0153   
3       12      Mataura      NZ     66.47     overcast clouds -46.1927   
4       13      Tsabong      BW     74.16           clear sky -26.0217   

        Lng            Hotel Name  
0  -89.7500  Auto hotel Esmeralda  
1  172.7902    Isles Sunset Lodge  
2   27.9116               Tu Casa  
3  168.8643         Ellie's Villa  
4   22.4010       Springbok Motel

In [8]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [9]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure

fig


Figure(layout=FigureLayout(height='420px'))

In [16]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Cabo San Lucas")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Cabo San Lucas")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Mulege")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Yaqui")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Alamos")]

vacation_start


City_ID            City Country  Max Temp Current Description      Lat  \
11       24  Cabo San Lucas      MX     82.51           clear sky  22.8909   

         Lng              Hotel Name  
11 -109.9124  Hotel Tesoro Los Cabos

In [47]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = tuple([vacation_start["Lat"].to_numpy(),vacation_start["Lng"].to_numpy()])
end = tuple([vacation_start["Lat"].to_numpy(),vacation_start["Lng"].to_numpy()])
stop1 = tuple([vacation_stop1["Lat"].to_numpy(),vacation_stop1["Lng"].to_numpy()])
stop2 = tuple([vacation_stop2["Lat"].to_numpy(),vacation_stop2["Lng"].to_numpy()])
stop3 = tuple([vacation_stop3["Lat"].to_numpy(),vacation_stop3["Lng"].to_numpy()])

print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

(array([22.8909]), array([-109.9124]))
(array([22.8909]), array([-109.9124]))
(array([26.8833]), array([-111.9833]))
(array([27.3667]), array([-110.1667]))
(array([27.0167]), array([-108.9333]))


In [53]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
import requests
# Import the API key.
from config import g_key

start = (22.8909,-109.9124)
stop = (22.8909,-109.9124)
stop1 = (26.8833,-111.9833)
stop2 =(27.3667,-110.1667)
stop3 = (27.0167,-108.9333)

# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
route = gmaps.directions_layer(start, stop, waypoints = [start,stop1,stop2,stop3,stop], travel_mode="DRIVING")
# Add the heatmap layer.
fig.add_layer(route)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [61]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID            City Country  Max Temp Current Description      Lat  \
0       24  Cabo San Lucas      MX     82.51           clear sky  22.8909   
1      505          Mulege      MX     76.17       broken clouds  26.8833   
2      661           Yaqui      MX     79.09          few clouds  27.3667   
3      666          Alamos      MX     79.72          few clouds  27.0167   

        Lng              Hotel Name  
0 -109.9124  Hotel Tesoro Los Cabos  
1 -111.9833            Casa Granada  
2 -110.1667                     NaN  
3 -108.9333             Luz del Sol

In [62]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [64]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))